# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.srcs/sources_1/ip/c2c_gth_7p8125g/c2c_gth_7p8125g.xci
# IP: The module: 'c2c_gth_7p8125g' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/ip/c2c_gth_7p8125g/synth/c2c_gth_7p8125g_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c2c_gth_7p8125g'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/ip/c2c_gth_7p8125g/synth/c2c_gth_7p8125g.xdc
# XDC: The top module name and the constraint reference have the same name: 'c2c_gth_7p8125g'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.srcs/sources_1/ip/c2c_gth_7p8125g/c2c_gth_7p8125g.xci
# IP: The module: 'c2c_gth_7p8125g' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/ip/c2c_gth_7p8125g/synth/c2c_gth_7p8125g_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c2c_gth_7p8125g'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/ip/c2c_gth_7p8125g/synth/c2c_gth_7p8125g.xdc
# XDC: The top module name and the constraint reference have the same name: 'c2c_gth_7p8125g'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
