# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_5_0/design_1_axis_data_fifo_5_0.xci
# IP: The module: 'design_1_axis_data_fifo_5_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/ip/design_1_axis_data_fifo_5_0/design_1_axis_data_fifo_5_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axis_data_fifo_5_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_5_0/design_1_axis_data_fifo_5_0.xci
# IP: The module: 'design_1_axis_data_fifo_5_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/ip/design_1_axis_data_fifo_5_0/design_1_axis_data_fifo_5_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axis_data_fifo_5_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
