# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_1_0/bd_0/ip/ip_0/constraints/xsdbm_cc_early.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0412_xsdbm_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_1_0/bd_0/ip/ip_0/constraints/xsdbm_cc_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0412_xsdbm_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_1_0/bd_0/ip/ip_0/constraints/xsdbm_gc_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0412_xsdbm_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_1_0/bd_0/ip/ip_0/bd_0412_xsdbm_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0412_xsdbm_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_1_0/bd_0/ip/ip_0/constraints/xsdbm_cc_early.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0412_xsdbm_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_1_0/bd_0/ip/ip_0/constraints/xsdbm_cc_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0412_xsdbm_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_1_0/bd_0/ip/ip_0/constraints/xsdbm_gc_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0412_xsdbm_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_1_0/bd_0/ip/ip_0/bd_0412_xsdbm_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0412_xsdbm_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
