# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/7015_primary.xdc

# XDC: imports/new/Kria_K26_SOM_Rev1.xdc

# XDC: imports/new/c2c_mgt.xdc

# XDC: imports/new/debug.xdc

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/xdc/async.xdc

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/xdc/top.xdc

# IP: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/iprepo/csum_tx/src/csum_fifo_fifo_generator_0_0/csum_fifo_fifo_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==csum_fifo_fifo_generator_0_0 || ORIG_REF_NAME==csum_fifo_fifo_generator_0_0} -quiet] -quiet

# IP: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/iprepo/csum_tx/src/data_fifo_axis_data_fifo_0_0/data_fifo_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_fifo_axis_data_fifo_0_0 || ORIG_REF_NAME==data_fifo_axis_data_fifo_0_0} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_chip2chip_0_0/design_1_axi_chip2chip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_chip2chip_0_0 || ORIG_REF_NAME==design_1_axi_chip2chip_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_chip2chip_1_0/design_1_axi_chip2chip_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_chip2chip_1_0 || ORIG_REF_NAME==design_1_axi_chip2chip_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axisafety_1_0/design_1_axisafety_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axisafety_1_0 || ORIG_REF_NAME==design_1_axisafety_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axisafety_2_0/design_1_axisafety_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axisafety_2_0 || ORIG_REF_NAME==design_1_axisafety_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_1_0/design_1_axi_bram_ctrl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_1_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_i2cSlave_0_0/design_1_i2cSlave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_i2cSlave_0_0 || ORIG_REF_NAME==design_1_i2cSlave_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_i2cSlave_1_0/design_1_i2cSlave_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_i2cSlave_1_0 || ORIG_REF_NAME==design_1_i2cSlave_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_1 || ORIG_REF_NAME==design_1_axi_gpio_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ipmb_watchdog_0_0/design_1_ipmb_watchdog_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ipmb_watchdog_0_0 || ORIG_REF_NAME==design_1_ipmb_watchdog_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_i2c_switch_dual_0_0/design_1_i2c_switch_dual_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_i2c_switch_dual_0_0 || ORIG_REF_NAME==design_1_i2c_switch_dual_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_2_0/design_1_system_ila_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_2_0 || ORIG_REF_NAME==design_1_system_ila_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_i2c_master_0_4/design_1_i2c_master_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_i2c_master_0_4 || ORIG_REF_NAME==design_1_i2c_master_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_jtag_0_0/design_1_axi_jtag_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_jtag_0_0 || ORIG_REF_NAME==design_1_axi_jtag_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_jtag_1_0/design_1_axi_jtag_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_jtag_1_0 || ORIG_REF_NAME==design_1_axi_jtag_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axisafety_2_1/design_1_axisafety_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axisafety_2_1 || ORIG_REF_NAME==design_1_axisafety_2_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_0 || ORIG_REF_NAME==design_1_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_6/design_1_xlconcat_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_6 || ORIG_REF_NAME==design_1_xlconcat_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_2/design_1_proc_sys_reset_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_2 || ORIG_REF_NAME==design_1_proc_sys_reset_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_2_0/design_1_proc_sys_reset_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_2_0 || ORIG_REF_NAME==design_1_proc_sys_reset_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_1/design_1_axi_bram_ctrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_1 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_1_0/design_1_axi_interconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_1_0 || ORIG_REF_NAME==design_1_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_1_1/design_1_axi_interconnect_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_1_1 || ORIG_REF_NAME==design_1_axi_interconnect_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_4/design_1_xbar_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_4 || ORIG_REF_NAME==design_1_xbar_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_1_2/design_1_axi_interconnect_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_1_2 || ORIG_REF_NAME==design_1_axi_interconnect_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_2_0/design_1_axi_interconnect_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_2_0 || ORIG_REF_NAME==design_1_axi_interconnect_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_4_0/design_1_axi_interconnect_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_4_0 || ORIG_REF_NAME==design_1_axi_interconnect_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_5/design_1_xbar_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_5 || ORIG_REF_NAME==design_1_xbar_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_management_wiz_0_0/design_1_system_management_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_management_wiz_0_0 || ORIG_REF_NAME==design_1_system_management_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debug_bridge_0_0/design_1_debug_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_debug_bridge_0_0 || ORIG_REF_NAME==design_1_debug_bridge_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debug_bridge_1_0/design_1_debug_bridge_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_debug_bridge_1_0 || ORIG_REF_NAME==design_1_debug_bridge_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_iic_0_0 || ORIG_REF_NAME==design_1_axi_iic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_iic_1_0/design_1_axi_iic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_iic_1_0 || ORIG_REF_NAME==design_1_axi_iic_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_iic_2_0/design_1_axi_iic_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_iic_2_0 || ORIG_REF_NAME==design_1_axi_iic_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_iic_3_0/design_1_axi_iic_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_iic_3_0 || ORIG_REF_NAME==design_1_axi_iic_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_iic_3_1/design_1_axi_iic_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_iic_3_1 || ORIG_REF_NAME==design_1_axi_iic_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ila_0_0 || ORIG_REF_NAME==design_1_ila_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pok_alarm_0_0/design_1_pok_alarm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_pok_alarm_0_0 || ORIG_REF_NAME==design_1_pok_alarm_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg_bank_0_0/design_1_reg_bank_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reg_bank_0_0 || ORIG_REF_NAME==design_1_reg_bank_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_jtag_logic_0_0/design_1_jtag_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_jtag_logic_0_0 || ORIG_REF_NAME==design_1_jtag_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_jtag_logic_0_1/design_1_jtag_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_jtag_logic_0_1 || ORIG_REF_NAME==design_1_jtag_logic_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_jtag_0_0/design_1_axis_jtag_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_jtag_0_0 || ORIG_REF_NAME==design_1_axis_jtag_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_cntrl_strm_rd_0_0/design_1_cntrl_strm_rd_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_cntrl_strm_rd_0_0 || ORIG_REF_NAME==design_1_cntrl_strm_rd_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_csum_rx_rss_0_0/design_1_csum_rx_rss_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_csum_rx_rss_0_0 || ORIG_REF_NAME==design_1_csum_rx_rss_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pkt_overflow_logic_0_0/design_1_pkt_overflow_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_pkt_overflow_logic_0_0 || ORIG_REF_NAME==design_1_pkt_overflow_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_1/design_1_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_1 || ORIG_REF_NAME==design_1_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tdest_align_0_0/design_1_tdest_align_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_tdest_align_0_0 || ORIG_REF_NAME==design_1_tdest_align_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tdest_mapper_0_0/design_1_tdest_mapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_tdest_mapper_0_0 || ORIG_REF_NAME==design_1_tdest_mapper_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_reduced_logic_0_0/design_1_util_reduced_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_reduced_logic_0_0 || ORIG_REF_NAME==design_1_util_reduced_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_reduced_logic_0_1/design_1_util_reduced_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_reduced_logic_0_1 || ORIG_REF_NAME==design_1_util_reduced_logic_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_reduced_logic_0_2/design_1_util_reduced_logic_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_reduced_logic_0_2 || ORIG_REF_NAME==design_1_util_reduced_logic_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_reduced_logic_2_0/design_1_util_reduced_logic_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_reduced_logic_2_0 || ORIG_REF_NAME==design_1_util_reduced_logic_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_reduced_logic_3_0/design_1_util_reduced_logic_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_reduced_logic_3_0 || ORIG_REF_NAME==design_1_util_reduced_logic_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_0 || ORIG_REF_NAME==design_1_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_1/design_1_util_vector_logic_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_1 || ORIG_REF_NAME==design_1_util_vector_logic_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_2/design_1_util_vector_logic_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_2 || ORIG_REF_NAME==design_1_util_vector_logic_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_3/design_1_util_vector_logic_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_3 || ORIG_REF_NAME==design_1_util_vector_logic_1_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_1/design_1_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_1 || ORIG_REF_NAME==design_1_xlconcat_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_2/design_1_xlconcat_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_2 || ORIG_REF_NAME==design_1_xlconcat_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_3/design_1_xlconcat_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_3 || ORIG_REF_NAME==design_1_xlconcat_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_4/design_1_xlconcat_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_4 || ORIG_REF_NAME==design_1_xlconcat_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_5/design_1_xlconcat_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_5 || ORIG_REF_NAME==design_1_xlconcat_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mcdma_0_0/design_1_axi_mcdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_mcdma_0_0 || ORIG_REF_NAME==design_1_axi_mcdma_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_1_0/design_1_axis_data_fifo_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_1_0 || ORIG_REF_NAME==design_1_axis_data_fifo_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_2_0/design_1_axis_data_fifo_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_2_0 || ORIG_REF_NAME==design_1_axis_data_fifo_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_3_0/design_1_axis_data_fifo_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_3_0 || ORIG_REF_NAME==design_1_axis_data_fifo_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_4_0/design_1_axis_data_fifo_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_4_0 || ORIG_REF_NAME==design_1_axis_data_fifo_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_5_0/design_1_axis_data_fifo_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_5_0 || ORIG_REF_NAME==design_1_axis_data_fifo_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tx_csum_0_1/design_1_tx_csum_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_tx_csum_0_1 || ORIG_REF_NAME==design_1_tx_csum_0_1} -quiet] -quiet

# IP: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/iprepo/csum_tx/src/csum_fifo_fifo_generator_0_0/csum_fifo_fifo_generator_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==csum_fifo_fifo_generator_0_0 || ORIG_REF_NAME==csum_fifo_fifo_generator_0_0} -quiet] -quiet

# IP: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/iprepo/csum_tx/src/data_fifo_axis_data_fifo_0_0/data_fifo_axis_data_fifo_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_fifo_axis_data_fifo_0_0 || ORIG_REF_NAME==data_fifo_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_3/design_1_proc_sys_reset_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_3 || ORIG_REF_NAME==design_1_proc_sys_reset_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_3/design_1_xbar_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_3 || ORIG_REF_NAME==design_1_xbar_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_0/design_1_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_0 || ORIG_REF_NAME==design_1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_0 || ORIG_REF_NAME==design_1_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_0_0 || ORIG_REF_NAME==design_1_system_ila_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_1_0/design_1_system_ila_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_1_0 || ORIG_REF_NAME==design_1_system_ila_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_1/design_1_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_1 || ORIG_REF_NAME==design_1_xlconstant_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_2/design_1_xlconstant_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_2 || ORIG_REF_NAME==design_1_xlconstant_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xxv_ethernet_0_0/design_1_xxv_ethernet_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xxv_ethernet_0_0 || ORIG_REF_NAME==design_1_xxv_ethernet_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_regslice_280/design_1_s00_regslice_280.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_280 || ORIG_REF_NAME==design_1_s00_regslice_280} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_data_fifo_280/design_1_s00_data_fifo_280.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s00_data_fifo_280 || ORIG_REF_NAME==design_1_s00_data_fifo_280} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_regslice_281/design_1_s00_regslice_281.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_281 || ORIG_REF_NAME==design_1_s00_regslice_281} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_data_fifo_281/design_1_s00_data_fifo_281.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s00_data_fifo_281 || ORIG_REF_NAME==design_1_s00_data_fifo_281} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_0 || ORIG_REF_NAME==design_1_auto_us_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_0/design_1_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_ds_0 || ORIG_REF_NAME==design_1_auto_ds_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_cc_0 || ORIG_REF_NAME==design_1_auto_cc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_cc_1 || ORIG_REF_NAME==design_1_auto_cc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_2/design_1_auto_cc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_cc_2 || ORIG_REF_NAME==design_1_auto_cc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_3/design_1_auto_cc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_cc_3 || ORIG_REF_NAME==design_1_auto_cc_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_regslice_282/design_1_s00_regslice_282.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_282 || ORIG_REF_NAME==design_1_s00_regslice_282} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_data_fifo_282/design_1_s00_data_fifo_282.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s00_data_fifo_282 || ORIG_REF_NAME==design_1_s00_data_fifo_282} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_1/design_1_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_ds_1 || ORIG_REF_NAME==design_1_auto_ds_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_regslice_283/design_1_s00_regslice_283.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_283 || ORIG_REF_NAME==design_1_s00_regslice_283} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_data_fifo_283/design_1_s00_data_fifo_283.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s00_data_fifo_283 || ORIG_REF_NAME==design_1_s00_data_fifo_283} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_ds_2/design_1_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_ds_2 || ORIG_REF_NAME==design_1_auto_ds_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s01_regslice_0/design_1_s01_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s01_regslice_0 || ORIG_REF_NAME==design_1_s01_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s01_data_fifo_0/design_1_s01_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s01_data_fifo_0 || ORIG_REF_NAME==design_1_s01_data_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m00_regslice_0/design_1_m00_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_m00_regslice_0 || ORIG_REF_NAME==design_1_m00_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m01_regslice_0/design_1_m01_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_m01_regslice_0 || ORIG_REF_NAME==design_1_m01_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m02_regslice_0/design_1_m02_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_m02_regslice_0 || ORIG_REF_NAME==design_1_m02_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_2 || ORIG_REF_NAME==design_1_auto_pc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m03_regslice_0/design_1_m03_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_m03_regslice_0 || ORIG_REF_NAME==design_1_m03_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_4/design_1_auto_cc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_cc_4 || ORIG_REF_NAME==design_1_auto_cc_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_3 || ORIG_REF_NAME==design_1_auto_pc_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_5/design_1_auto_cc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_cc_5 || ORIG_REF_NAME==design_1_auto_cc_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_4/design_1_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_4 || ORIG_REF_NAME==design_1_auto_pc_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_5/design_1_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_5 || ORIG_REF_NAME==design_1_auto_pc_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_6/design_1_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_6 || ORIG_REF_NAME==design_1_auto_pc_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_7/design_1_auto_pc_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_7 || ORIG_REF_NAME==design_1_auto_pc_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_8/design_1_auto_pc_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_8 || ORIG_REF_NAME==design_1_auto_pc_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_9/design_1_auto_pc_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_9 || ORIG_REF_NAME==design_1_auto_pc_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_10/design_1_auto_pc_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_10 || ORIG_REF_NAME==design_1_auto_pc_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_11/design_1_auto_pc_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_11 || ORIG_REF_NAME==design_1_auto_pc_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_1 || ORIG_REF_NAME==design_1_auto_us_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_2/design_1_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_2 || ORIG_REF_NAME==design_1_auto_us_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_3/design_1_auto_us_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_3 || ORIG_REF_NAME==design_1_auto_us_3} -quiet] -quiet

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/tmp_edit_project.gen/sources_1/ip/csum_fifo_fifo_generator_0_0/csum_fifo_fifo_generator_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==csum_fifo_fifo_generator_0_0 || ORIG_REF_NAME==csum_fifo_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/tmp_edit_project.gen/sources_1/ip/csum_fifo_fifo_generator_0_0/csum_fifo_fifo_generator_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==csum_fifo_fifo_generator_0_0 || ORIG_REF_NAME==csum_fifo_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/tmp_edit_project.gen/sources_1/ip/csum_fifo_fifo_generator_0_0/csum_fifo_fifo_generator_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==csum_fifo_fifo_generator_0_0 || ORIG_REF_NAME==csum_fifo_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/tmp_edit_project.gen/sources_1/ip/csum_fifo_fifo_generator_0_0/csum_fifo_fifo_generator_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==csum_fifo_fifo_generator_0_0 || ORIG_REF_NAME==csum_fifo_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/design_1_ooc.xdc
