# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.srcs/sources_1/bd/design_1/ip/design_1_tx_csum_0_1/design_1_tx_csum_0_1.xci
# IP: The module: 'design_1_tx_csum_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/iprepo/csum_tx/src/csum_fifo_fifo_generator_0_0/csum_fifo_fifo_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==csum_fifo_fifo_generator_0_0 || ORIG_REF_NAME==csum_fifo_fifo_generator_0_0} -quiet] -quiet

# IP: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/iprepo/csum_tx/src/data_fifo_axis_data_fifo_0_0/data_fifo_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_fifo_axis_data_fifo_0_0 || ORIG_REF_NAME==data_fifo_axis_data_fifo_0_0} -quiet] -quiet

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/tmp_edit_project.gen/sources_1/ip/csum_fifo_fifo_generator_0_0/csum_fifo_fifo_generator_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==csum_fifo_fifo_generator_0_0 || ORIG_REF_NAME==csum_fifo_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/tmp_edit_project.gen/sources_1/ip/csum_fifo_fifo_generator_0_0/csum_fifo_fifo_generator_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==csum_fifo_fifo_generator_0_0 || ORIG_REF_NAME==csum_fifo_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/ip/design_1_tx_csum_0_1/design_1_tx_csum_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_tx_csum_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.srcs/sources_1/bd/design_1/ip/design_1_tx_csum_0_1/design_1_tx_csum_0_1.xci
# IP: The module: 'design_1_tx_csum_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/iprepo/csum_tx/src/csum_fifo_fifo_generator_0_0/csum_fifo_fifo_generator_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==csum_fifo_fifo_generator_0_0 || ORIG_REF_NAME==csum_fifo_fifo_generator_0_0} -quiet] -quiet

# IP: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/iprepo/csum_tx/src/data_fifo_axis_data_fifo_0_0/data_fifo_axis_data_fifo_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_fifo_axis_data_fifo_0_0 || ORIG_REF_NAME==data_fifo_axis_data_fifo_0_0} -quiet] -quiet

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/tmp_edit_project.gen/sources_1/ip/csum_fifo_fifo_generator_0_0/csum_fifo_fifo_generator_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==csum_fifo_fifo_generator_0_0 || ORIG_REF_NAME==csum_fifo_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/tmp_edit_project.gen/sources_1/ip/csum_fifo_fifo_generator_0_0/csum_fifo_fifo_generator_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==csum_fifo_fifo_generator_0_0 || ORIG_REF_NAME==csum_fifo_fifo_generator_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/ip/design_1_tx_csum_0_1/design_1_tx_csum_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_tx_csum_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
