# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.srcs/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0/design_1_debug_bridge_0_0.xci
# IP: The module: 'design_1_debug_bridge_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0/bd_0/bd_c443.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c443 || ORIG_REF_NAME==bd_c443} -quiet] -quiet

# IP: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0/bd_0/ip/ip_0/bd_c443_axi_jtag_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c443_axi_jtag_0 || ORIG_REF_NAME==bd_c443_axi_jtag_0} -quiet] -quiet

# IP: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0/bd_0/ip/ip_1/bd_c443_bsip_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c443_bsip_0 || ORIG_REF_NAME==bd_c443_bsip_0} -quiet] -quiet

# IP: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0/bd_0/ip/ip_2/bd_c443_bs_switch_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c443_bs_switch_1_0 || ORIG_REF_NAME==bd_c443_bs_switch_1_0} -quiet] -quiet

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0/bd_0/bd_c443_ooc.xdc

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0/design_1_debug_bridge_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_debug_bridge_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.srcs/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0/design_1_debug_bridge_0_0.xci
# IP: The module: 'design_1_debug_bridge_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0/bd_0/bd_c443.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c443 || ORIG_REF_NAME==bd_c443} -quiet] -quiet

# IP: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0/bd_0/ip/ip_0/bd_c443_axi_jtag_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c443_axi_jtag_0 || ORIG_REF_NAME==bd_c443_axi_jtag_0} -quiet] -quiet

# IP: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0/bd_0/ip/ip_1/bd_c443_bsip_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c443_bsip_0 || ORIG_REF_NAME==bd_c443_bsip_0} -quiet] -quiet

# IP: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0/bd_0/ip/ip_2/bd_c443_bs_switch_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c443_bs_switch_1_0 || ORIG_REF_NAME==bd_c443_bs_switch_1_0} -quiet] -quiet

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0/bd_0/bd_c443_ooc.xdc

# XDC: /home/agreshil/vivado_projects/fw_i2c_master/apex/control/apex_kria/apex_kria.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0/design_1_debug_bridge_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_debug_bridge_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
